
;;;; bindings.el


(keyboard-translate ?\C-h ?\C-?)
(global-set-key "\C-ch" 'help-command)
(global-set-key "\C-cd" 'pwd)
(global-set-key "\C-csg" 'grep)
(global-set-key "\C-csl" 'lgrep)
(global-set-key "\C-csr" 'rgrep)
(global-set-key "\C-csf" 'grep-find)
(global-set-key "\C-cso" 'occur)
(global-set-key "\C-ct" 'eshell)
(global-set-key "\C-cw" 'eww)
(global-set-key "\M-Y" 'yank-pop-forwards)
(global-set-key (kbd "M-+") 'duplicate-and-comment-out)
(global-set-key (kbd "C-S-n") 'next-line-scroll-up)
(global-set-key (kbd "C-S-p") 'previous-line-scroll-down)
(global-set-key (kbd "C->") 'next-error)
(global-set-key (kbd "C-<") 'previous-error)
(global-set-key (kbd "C-:") 'split-window-below)
(global-set-key (kbd "C-M-:") 'split-window-right)
(global-set-key (kbd "C-*") 'delete-window)
(global-set-key (kbd "C-M-*") 'delete-other-windows)
(global-set-key (kbd "C-,") 'other-window)
(global-set-key (kbd "C-M-,") (lambda () (interactive) (other-window -1)))
(global-set-key (kbd "C-c :") 'manipulate-window)
(global-set-key (kbd "C-;") 'make-frame)
(global-set-key (kbd "C-+") 'delete-frame)
(global-set-key (kbd "C-.") 'other-frame)
(global-set-key (kbd "C-M-.") (lambda () (interactive) (other-frame -1)))
(global-set-key (kbd "C-c ;") 'manipulate-frame)
